-- ShopSphere Phase 2A: authentication foundation.
-- Users table for registration. Only BCrypt password hashes are ever stored.
-- No plain-text passwords and no passwordHash exposure in any API response.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100)              NOT NULL,
    email         VARCHAR(255)              NOT NULL,
    password_hash VARCHAR(100)              NOT NULL,
    role          VARCHAR(20)               NOT NULL DEFAULT 'CUSTOMER',
    created_at    TIMESTAMP WITH TIME ZONE  NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE  NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email)
);