-- ShopSphere Phase 3A: product catalog foundation.
-- Categories and products tables only; catalog APIs arrive in a later phase.
-- Prices are stored as NUMERIC(12,2). SKUs and category names are unique.
-- Product -> category is a required (restrict) FK: deleting a category that
-- still has products must fail rather than silently orphan or delete them.

CREATE TABLE categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)             NOT NULL,
    description VARCHAR(1000),
    active      BOOLEAN                  NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_categories_name UNIQUE (name)
);

CREATE TABLE products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku         VARCHAR(64)              NOT NULL,
    name        VARCHAR(150)             NOT NULL,
    description VARCHAR(2000),
    price       NUMERIC(12, 2)           NOT NULL,
    active      BOOLEAN                  NOT NULL DEFAULT TRUE,
    category_id BIGINT                   NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_products_sku UNIQUE (sku),
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (id)
);

-- PostgreSQL does not index FK columns automatically; the catalog queries by
-- category and by active flag, so these indexes support the future APIs.
CREATE INDEX idx_products_category_id ON products (category_id);
CREATE INDEX idx_products_active ON products (active);
CREATE INDEX idx_categories_active ON categories (active);