-- ShopSphere Phase 5: Inventory, Orders and Payments.
-- Available stock = quantity - reserved_qty; both are guarded non-negative by
-- CHECK constraints (and by the entity, which never lets them go negative).
-- Orders snapshot the shipping address and the item name/SKU/price at purchase
-- time. One payment per order (unique order_id). Existing products are seeded
-- with a default stock of 100 units and a reorder threshold of 10; products
-- created later get inventory lazily from the service layer.

CREATE TABLE inventories (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id        BIGINT                   NOT NULL,
    quantity          INTEGER                  NOT NULL,
    reserved_qty      INTEGER                  NOT NULL DEFAULT 0,
    reorder_threshold INTEGER                  NOT NULL DEFAULT 0,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_inventories_product_id UNIQUE (product_id),
    CONSTRAINT fk_inventories_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT,
    CONSTRAINT chk_inventories_quantity CHECK (quantity >= 0),
    CONSTRAINT chk_inventories_reserved_qty CHECK (reserved_qty >= 0),
    CONSTRAINT chk_inventories_reorder_threshold CHECK (reorder_threshold >= 0)
);
CREATE INDEX idx_inventories_product_id ON inventories (product_id);

-- Seed inventory for every product that exists at migration time so existing
-- catalog data keeps working unchanged.
INSERT INTO inventories (product_id, quantity, reserved_qty, reorder_threshold, created_at, updated_at)
SELECT p.id, 100, 0, 10, now(), now()
FROM products p;

CREATE TABLE orders (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT                    NOT NULL,
    order_number   VARCHAR(32)               NOT NULL,
    subtotal       NUMERIC(12, 2)            NOT NULL,
    discount       NUMERIC(12, 2)            NOT NULL,
    shipping_fee   NUMERIC(12, 2)            NOT NULL,
    total_amount   NUMERIC(12, 2)            NOT NULL,
    recipient_name VARCHAR(100)              NOT NULL,
    phone          VARCHAR(30)               NOT NULL,
    address_line1  VARCHAR(255)              NOT NULL,
    address_line2  VARCHAR(255),
    city           VARCHAR(100)              NOT NULL,
    state          VARCHAR(100)              NOT NULL,
    postal_code    VARCHAR(20)               NOT NULL,
    country        VARCHAR(100)              NOT NULL,
    order_status   VARCHAR(20)               NOT NULL,
    payment_status VARCHAR(20)               NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_orders_order_number UNIQUE (order_number),
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_orders_subtotal CHECK (subtotal >= 0),
    CONSTRAINT chk_orders_discount CHECK (discount >= 0),
    CONSTRAINT chk_orders_shipping_fee CHECK (shipping_fee >= 0),
    CONSTRAINT chk_orders_total_amount CHECK (total_amount >= 0)
);
CREATE INDEX idx_orders_user_id ON orders (user_id);
CREATE INDEX idx_orders_order_status ON orders (order_status);

CREATE TABLE order_items (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id          BIGINT           NOT NULL,
    product_id        BIGINT           NOT NULL,
    product_name      VARCHAR(150)     NOT NULL,
    sku               VARCHAR(64)      NOT NULL,
    price_at_purchase NUMERIC(12, 2)   NOT NULL,
    quantity          INTEGER          NOT NULL,
    line_total        NUMERIC(12, 2)   NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT,
    CONSTRAINT chk_order_items_quantity CHECK (quantity > 0),
    CONSTRAINT chk_order_items_price CHECK (price_at_purchase >= 0),
    CONSTRAINT chk_order_items_line_total CHECK (line_total >= 0)
);
CREATE INDEX idx_order_items_order_id ON order_items (order_id);
CREATE INDEX idx_order_items_product_id ON order_items (product_id);

CREATE TABLE payments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            BIGINT                    NOT NULL,
    amount              NUMERIC(12, 2)            NOT NULL,
    payment_status      VARCHAR(20)               NOT NULL,
    provider            VARCHAR(50)               NOT NULL,
    provider_payment_id VARCHAR(100),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_payments_order_id UNIQUE (order_id),
    CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT chk_payments_amount CHECK (amount >= 0)
);
CREATE INDEX idx_payments_order_id ON payments (order_id);
CREATE INDEX idx_payments_provider_payment_id ON payments (provider_payment_id);
